version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - db_env.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  celery:
    restart: always
    build: .
    command: ["celery", "-A", "EcoMail", "worker", "-l", "info"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - app
  celery-beat:
    build: .
    command:
        bash -c "celery -A EcoMail beat"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
volumes:
  pgdata: