# Generated by Django 3.2.12 on 2022-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='s3Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognitoId', models.CharField(max_length=255)),
                ('link', models.TextField()),
            ],
        ),
    ]
