# Generated by Django 3.2.12 on 2022-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3images',
            name='link',
            field=models.TextField(default='/static/default.png'),
        ),
    ]
